version: "3.1"

networks:
  pokemon-rest-net:

services:
  db:
    container_name: mongoDB
    image: mongo:latest

    volumes:
      - ./pokeData:/data/db
    networks:
      - pokemon-rest-net 

    environment:
      - MONGO_INITDB_DATABASE= Pokemon
    
  node:
    image: node:latest
    
    networks:
      - pokemon-rest-net
    ports:
      - 80:8000

    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules

    working_dir: /usr/src/app
  
    depends_on:
      - db
  
    command: npm start
