version: "3.1"

networks:
  pokemon-rest-net:

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    
    networks:
      - pokemon-rest-net 
    volumes:
      - ./pokeData:/data/db

    environment:
      - MONGO_INITDB_DATABASE= Pokemon
    
  node:
    image: node:latest

    networks:
      - pokemon-rest-net
    ports:
      - 80:8000

    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  
    depends_on:
      - db